services:
  instagram-api:
    build: .
    restart: always
    #network_mode: "host"
    ports:
      - "8026:8026"
    #env_file:
    #  - .env
    environment:
      - CAMOUFOX_HEADLESS=virtual
      - CAMOUFOX_OS=windows
      - CAMOUFOX_LOCALE=en-US
      - CAMOUFOX_HUMANIZE=true
      - CAMOUFOX_GEOIP=false
      - CAMOUFOX_PERSISTENT=true
      - CAMOUFOX_USER_DATA_DIR=/app/camoufox-profile

    volumes:
      - camoufox-profile:/app/camoufox-profile

volumes:
  camoufox-profile: